services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sample'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=sample'
    ports:
      - '33067:3306'
    volumes:
      - mysql_data_batch:/var/lib/mysql

volumes:
  mysql_data_batch: